from datetime import datetime

def generate_report(invoice, findings, compliance, verification):

    # ---------- Summary ----------

    high = sum(
        1 for finding in findings
        if finding.get("severity") == "High"
    )

    medium = sum(
        1 for finding in findings
        if finding.get("severity") == "Medium"
    )

    low = sum(
        1 for finding in findings
        if finding.get("severity") == "Low"
    )

    # ---------- Final Decision ----------

    if high > 0:
        decision = "REJECT"
        reason = "One or more high-severity findings were detected."

    elif compliance["status"] == "Failed":
        decision = "REVIEW"
        reason = "Compliance violations require manual review."

    else:
        decision = "APPROVE"
        reason = "No critical audit issues were detected."

    # ---------- Build Report Text ----------

    report_text = f"""
====================================================
                    AUDIT REPORT
====================================================

Invoice Details
----------------------------------------------------
Invoice Number : {invoice.get("invoice_number")}
Vendor         : {invoice.get("vendor")}
Amount         : ₹{invoice.get("amount")}
Invoice Date   : {invoice.get("date")}
GST            : {invoice.get("gst")}

====================================================
ANOMALY DETECTION
====================================================

Total Findings : {len(findings)}
High           : {high}
Medium         : {medium}
Low            : {low}

"""

    for index, finding in enumerate(findings, start=1):

        report_text += f"""
            Finding {index}

            Rule      : {finding.get("rule")}
            Severity  : {finding.get("severity")}
            Message   : {finding.get("message")}
            Evidence  : {finding.get("evidence")}

            """

    report_text += f"""
            ====================================================
            COMPLIANCE
            ====================================================

            Status : {compliance.get("status")}

            Violations:
            """

    violations = compliance.get("violations", [])

    if violations:

        for violation in violations:
            report_text += f"- {violation}\n"

    else:
        report_text += "None\n"

    report_text += f"""

            ====================================================
            VERIFICATION
            ====================================================

            Verified      : {verification.get("verified")}
            Confidence    : {verification.get("confidence")}%
            Overall Risk  : {verification.get("overall_risk")}

            ====================================================
            FINAL DECISION
            ====================================================

            Decision : {decision}

            Reason:
            {reason}

            ====================================================
            Generated by AuditIQ
            Generated at: {datetime.now().strftime("%d-%m-%Y %H:%M:%S")}
            ====================================================
            """

    return {

        "invoice": invoice,

        "summary": {
            "total_findings": len(findings),
            "high": high,
            "medium": medium,
            "low": low,
        },

        "findings": findings,

        "compliance": compliance,

        "verification": verification,

        "final_decision": decision,

        "reason": reason,

        "generated_at": datetime.now().isoformat(),

        "report_text": report_text
    }